export function buildSeedLeads(funnelClinicalId, funnelLabId) {
  return [
    {
      id: 'seed-1',
      name: 'Dr. Sarah Chen',
      company: 'Pacific Research Associates',
      title: 'Principal Investigator',
      phone: '(619) 555-0142',
      email: 's.chen@pacificresearch.com',
      address: '4510 Executive Dr',
      city: 'San Diego',
      state: 'CA',
      zip: '92121',
      lat: 32.8969,
      lng: -117.2201,
      funnelId: funnelClinicalId,
      temperature: 'hot',
      notes: 'Met at DIA conference. Interested in Phase II oncology trials.',
    },
    {
      id: 'seed-2',
      name: 'James Whitfield',
      company: 'Midwest Clinical Partners',
      title: 'Site Director',
      phone: '(312) 555-0198',
      email: 'jwhitfield@midwestclinical.com',
      address: '233 S Wacker Dr',
      city: 'Chicago',
      state: 'IL',
      zip: '60606',
      lat: 41.8781,
      lng: -87.6298,
      funnelId: funnelClinicalId,
      temperature: 'warm',
      notes: 'Follow up next quarter about cardiology studies.',
    },
    {
      id: 'seed-3',
      name: 'Maria Gonzalez',
      company: 'Sunrise Trial Center',
      title: 'Clinical Research Coordinator',
      phone: '(305) 555-0167',
      email: 'mgonzalez@sunrisetrials.com',
      address: '1200 Brickell Ave',
      city: 'Miami',
      state: 'FL',
      zip: '33131',
      lat: 25.7617,
      lng: -80.1918,
      funnelId: funnelClinicalId,
      temperature: 'cool',
      notes: 'Requested protocol deck before scheduling call.',
    },
    {
      id: 'seed-4',
      name: 'Robert Kim',
      company: 'Northwest Investigational Site',
      title: 'Medical Director',
      phone: '(206) 555-0133',
      email: 'rkim@nwisite.org',
      address: '600 Broadway',
      city: 'Seattle',
      state: 'WA',
      zip: '98122',
      lat: 47.6062,
      lng: -122.3321,
      funnelId: funnelClinicalId,
      temperature: 'hot',
      notes: 'Ready to start feasibility review.',
    },
    {
      id: 'seed-5',
      name: 'Lisa Patel',
      company: 'Boston Academic Research Network',
      title: 'VP Clinical Operations',
      phone: '(617) 555-0188',
      email: 'lpatel@barnetwork.org',
      address: '75 Francis St',
      city: 'Boston',
      state: 'MA',
      zip: '02115',
      lat: 42.3355,
      lng: -71.1066,
      funnelId: funnelClinicalId,
      temperature: 'warm',
      notes: 'Multi-site opportunity — rheumatology focus.',
    },
    {
      id: 'seed-6',
      name: 'David Okonkwo',
      company: 'Metro Phase One Center',
      title: 'Site Manager',
      phone: '(212) 555-0155',
      email: 'dokonkwo@metrophase1.com',
      address: '350 5th Ave',
      city: 'New York',
      state: 'NY',
      zip: '10118',
      lat: 40.7484,
      lng: -73.9857,
      funnelId: funnelClinicalId,
      temperature: 'dead',
      notes: 'No budget this year. Revisit in 2027.',
    },
    {
      id: 'seed-7',
      name: 'Angela Torres',
      company: 'Apex Diagnostics Lab',
      title: 'Lab Director',
      phone: '(602) 555-0121',
      email: 'atorres@apexdiagnostics.com',
      address: '2929 N Central Ave',
      city: 'Phoenix',
      state: 'AZ',
      zip: '85012',
      lat: 33.4484,
      lng: -112.074,
      funnelId: funnelLabId,
      temperature: 'cool',
      notes: 'CLIA-certified. Specialty: molecular diagnostics.',
    },
    {
      id: 'seed-8',
      name: 'Michael Braun',
      company: 'Coastal Pathology',
      title: 'Operations Manager',
      phone: '(310) 555-0174',
      email: 'mbraun@coastalpath.com',
      address: '10940 Wilshire Blvd',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90024',
      lat: 34.0522,
      lng: -118.2437,
      funnelId: funnelLabId,
      temperature: 'warm',
      notes: 'High throughput lab. Good for central lab partnership.',
    },
    {
      id: 'seed-9',
      name: 'Jennifer Walsh',
      company: 'Precision Lab Sciences',
      title: 'Business Development',
      phone: '(512) 555-0190',
      email: 'jwalsh@precisionlabsci.com',
      address: '701 Brazos St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
      lat: 30.2672,
      lng: -97.7431,
      funnelId: funnelLabId,
      temperature: 'hot',
      notes: 'Wants pilot program proposal by end of month.',
    },
    {
      id: 'seed-10',
      name: 'Thomas Reed',
      company: 'Rocky Mountain Reference Lab',
      title: 'CEO',
      phone: '(303) 555-0148',
      email: 'treed@rmreferencelab.com',
      address: '1700 Broadway',
      city: 'Denver',
      state: 'CO',
      zip: '80290',
      lat: 39.7392,
      lng: -104.9903,
      funnelId: funnelLabId,
      temperature: 'warm',
      notes: 'Expanding toxicology panel capabilities.',
    },
    {
      id: 'seed-11',
      name: 'Patricia Nguyen',
      company: 'Gulf Coast Clinical Lab',
      title: 'Director of Sales',
      phone: '(713) 555-0162',
      email: 'pnguyen@gulfcoastlab.com',
      address: '1600 Smith St',
      city: 'Houston',
      state: 'TX',
      zip: '77002',
      lat: 29.7604,
      lng: -95.3698,
      funnelId: funnelLabId,
      temperature: 'dead',
      notes: 'Merged with competitor. No longer independent.',
    },
    {
      id: 'seed-12',
      name: 'Steven Alvarez',
      company: 'Valley Reference Diagnostics',
      title: 'Lab Manager',
      phone: '(408) 555-0139',
      email: 'salvarez@valleyrefdx.com',
      address: '1 Market St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
      lat: 37.7749,
      lng: -122.4194,
      funnelId: funnelLabId,
      temperature: 'cool',
      notes: 'Interested in sample logistics integration.',
    },
  ];
}

export async function seedDemoData(db) {
  const funnels = await db.getAllFunnels();
  const clinical = funnels.find((f) => f.name.includes('Clinical')) || funnels[0];
  const lab = funnels.find((f) => f.name.includes('Lab')) || funnels[1] || funnels[0];
  const now = new Date().toISOString();
  const seeds = buildSeedLeads(clinical.id, lab.id);
  for (const lead of seeds) {
    await db.putLead({ ...lead, createdAt: now, updatedAt: now });
  }
  await db.setMeta('seeded', true);
  return seeds.length;
}
